export const TOGGLE_FULLSCREEN = 'TOGGLE_FULLSCREEN';
export const DISABLE_FULLSCREEN = 'DISABLE_FULLSCREEN';

export const TOGGLE_LIGHTBOX = 'TOGGLE_LIGHTBOX';
export const DISABLE_LIGHTBOX = 'DISABLE_LIGHTBOX';

export const OPEN_SEARCH_PANEL = 'OPEN_SEARCH_PANEL';
export const CLOSE_SEARCH_PANEL = 'CLOSE_SEARCH_PANEL';

export const TOGGLE_TEMP_FULLSCREEN = 'TOGGLE_TEMP_FULLSCREEN';
export const DISABLE_TEMP_FULLSCREEN = 'DISABLE_TEMP_FULLSCREEN';

export const SET_INITIAL_RESPONSE = 'SET_INITIAL_RESPONSE';
export const SET_FINAL_RESPONSE = 'SET_FINAL_RESPONSE';
export const SET_PHOTOS_TO_RENDER = 'SET_PHOTOS_TO_RENDER';

export const TOGGLE_LOADING = 'TOGGLE_LOADING';
export const DISABLE_LOADING = 'DISABLE_LOADING';

export const TOGGLE_GALLERY_LOADING = 'TOGGLE_GALLERY_LOADING';
export const DISABLE_GALLERY_LOADING = 'DISABLE_GALLERY_LOADING';

export const SET_EVENT_CODE = 'SET_EVENT_CODE';
export const SET_ATTENDEE = 'SET_ATTENDEE';

export const SET_TOTAL_RESULTS = 'SET_TOTAL_RESULTS';

export const SET_SEARCH_RESULT = 'SET_SEARCH_RESULT';

export const SET_ALBUM_RESPONSE = 'SET_ALBUM_RESPONSE';

export const SET_XCSRF_TOKEN = 'SET_XCSRF_TOKEN';