export const TOGGLE_FULLSCREEN = 'TOGGLE_FULLSCREEN';
export const DISABLE_FULLSCREEN = 'DISABLE_FULLSCREEN';

export const TOGGLE_TEMP_FULLSCREEN = 'TOGGLE_TEMP_FULLSCREEN';
export const DISABLE_TEMP_FULLSCREEN = 'DISABLE_TEMP_FULLSCREEN';

export const SET_PUZZLES_RESPONSE = 'SET_PUZZLES_RESPONSE';
export const SET_PHOTOS_TO_RENDER = 'SET_PHOTOS_TO_RENDER';

export const TOGGLE_LOADING = 'TOGGLE_LOADING';
export const DISABLE_LOADING = 'DISABLE_LOADING';

export const TOGGLE_GALLERY_LOADING = 'TOGGLE_GALLERY_LOADING';
export const DISABLE_GALLERY_LOADING = 'DISABLE_GALLERY_LOADING';

export const ENABLE_FETCH_REQUEST = 'ENABLE_FETCH_REQUEST';
export const DISABLE_FETCH_REQUEST = 'DISABLE_FETCH_REQUEST';

export const SET_EVENT_CODE = 'SET_EVENT_CODE';
export const SET_ATTENDEE = 'SET_ATTENDEE';

export const SET_TOTAL_RESULTS = 'SET_TOTAL_RESULTS';

export const SET_ALBUMS_LIST = 'SET_ALBUMS_LIST';

export const SET_ALBUM_INFO = 'SET_ALBUM_INFO';

export const SET_XCSRF_TOKEN = 'SET_XCSRF_TOKEN';

export const SET_SELECTED_ALBUM_ID = 'SET_SELECTED_ALBUM_ID';

export const SET_ALBUM_OWNER_ID = 'SET_ALBUM_OWNER_ID';

export const SET_LANGUAGE = 'SET_LANGUAGE';

export const SET_PUZZLES = 'SET_PUZZLES';

export const SET_AUTHSTATUS = 'SET_AUTHSTATUS';

export const SET_BUTTON_TYPE = 'SET_BUTTON_TYPE';

export const TRIGGER_DOWNLOAD_ZIP = 'TRIGGER_DOWNLOAD_ZIP';